name: 'Qualys IaC GitHub Action'
author: 'Qualys'
description: 'Find and fix security and compliance issues in infrastructure code using Qualys IaC GitHub Action'
inputs:
  directory:
    description: 'directory with infrastructure code to scan'
    default: '.'
    required: false

runs:
  using: 'docker'
  image: 'dockerfile'
