name: 'Charchil Github Action'
author: 'Charchil'
description: 'Find and fix security and compliance issues in infrastructure code using charchil Action'
inputs:
  directory:
    description: 'directory with infrastructure code to scan'
    default: '.'
    required: false

runs:
  using: 'docker'
  image: 'dockerfile'
  args:
    - ${{ inputs.directory }}
